# Assignment: Python Basics
We assume you are using Python 3 in this course.

## Question 1

You've learned different data types in Python. Now, let's test your knowledge. 

You need to use to format strings. 

Write a program using the "f-strings" (https://realpython.com/python-f-strings/) and user input function to convert temperatures from Fahrenheit to Celsius. [Formula: Celsius = (Fahrenheit – 32)*5/9]

Hint: you may need int() or float() function

An example program output:
```
Please enter the temperature in Celcius: 140
140F is 60.0 in Celsius. 
```

In [ ]:
# an example of f-strings and user input function
username = input('What\'s your name? ')
print(f'Welcome, {username}!')

In [5]:
# complete your program here
f = float(input('Please enter the temperature in Fahrenheit: '))
c = (f - 32) * 5/9
print(f'{f} F is {c} in Celcius.')

Please enter the temperature in Fahrenheit: 32
32.0 F is 0.0 in Celcius.


Now, do the oppsoite by convert temperatures from Celsius to Fahrenheit.
Another example:
```
Please enter the temperature in Celcius: 60
60C is 140.0 in Fahrenheit. 
```

In [6]:
# complete your program here
c = float(input('Please enter the temperature in Celcius: '))
f = (c * (9/5) + 32)
print(f'{c} C is {f} in Farenheit.')

Please enter the temperature in Celcius: 0
0.0 C is 32.0 in Farenheit.


Next, let's make it a bit challenging by adding conditional statements to convert temperatures to and from Celsius, Fahrenheit. [Formula: Celsius/5 = (Fahrenheit – 32)/9]

An example program output:
```
Please enter the temperature: 60
Is this in Celsius or Fahrenheit? C
60C is 140 in Fahrenheit
```

Another example:
```
Please enter the temperature: 140
Is this Celsius or Fahrenheit? F
140F is 60 in Celsius
```

In [10]:
# complete your program here
d = float(input('Please enter the temperature: '))
m = input('Is this in Celsius or Fahrenheit? ').upper()
if m == 'C':
    f = (d * (9/5) + 32)
    print(f'{d} C is {f} in Farenheit.')
elif m == 'F':
    c = (d - 32) * 5/9
    print(f'{d} F is {c} in Celcius.')

Please enter the temperature: 0
Is this in Celsius or Fahrenheit? c
0.0 C is 32.0 in Farenheit.


## Question 2

Have some fun with strings.

In [2]:
sentence = "Talk is cheap. Show me the code - Linus Torvalds"

In [12]:
# Find the length of this sentence.
print(len(sentence))

48


In [13]:
# Convert the whole string to lower case. 
print(sentence.lower())

talk is cheap. show me the code - linus torvalds


In [3]:
# Extract a substring from the 10th character from left to the 10th character from right.
print(sentence[8:-9])

cheap. Show me the code - Linus


In [15]:
# Split the sentence into a list of substrings by space ' '. 
print(sentence.split(' '))

['Talk', 'is', 'cheap.', 'Show', 'me', 'the', 'code', '-', 'Linus', 'Torvalds']


In [17]:
# Given the sentence, output a list of words in lowercase (without punctuations). 
print(sentence.lower().replace('.',' ').replace('-',' ').split())

['talk', 'is', 'cheap', 'show', 'me', 'the', 'code', 'linus', 'torvalds']


In [18]:
# Count the total number of vowels in the sentence.
vowels = ['a', 'e', 'i', 'o', 'u']
vowel_count = 0
for char in sentence:
    if char.lower() in vowels:
        vowel_count += 1
print(vowel_count)

13


In [10]:
vowel_positions = [i for i in range(len(sentence)) if sentence[i].lower() in 'aeiou']
vowel_positions

[1, 5, 10, 11, 17, 21, 25, 28, 30, 35, 37, 41, 44]

## Question 3

Review list comprehension if needed: https://realpython.com/list-comprehension-python/

The formula for list comprehension is: `new_list = [expression for member in iterable (if conditional)]`

You need to do the following:

In [1]:
# Use a loop to create a list of 5 cube numbers and print the list：[0, 1, 8, 27, 64]
cubes = []
for i in range(5):
    cubes.append(i ** 3)
cubes

[0, 1, 8, 27, 64]

In [2]:
# Use list comprehension to create the same list
cubes = [i ** 3 for i in range(5)]
cubes

[0, 1, 8, 27, 64]

In [7]:
# Find the postions (indexes) of all vowels in a sentence using list comprehension
sentence = "Toto, I\'ve a feeling we\'re not in Kansas anymore. - THE WIZARD OF OZ (1939)"
vowel_positions = [i for i in range(len(sentence)) if sentence[i].lower() in 'aeiou']
vowel_positions

[1,
 3,
 6,
 9,
 11,
 14,
 15,
 17,
 22,
 25,
 28,
 31,
 35,
 38,
 41,
 45,
 47,
 54,
 57,
 59,
 63,
 66]

In [12]:
# Use a loop to create a list of first n numbers in the Fibonacci sequence
# [0, 1, 1, 2, 3, 5, 8, ...] 
fibonacci = []
n = int(input('How many numbers do you want? '))
# add your code here
a, b = 0, 1
for i in range(n):
    fibonacci.append(a)
    a, b = b, a+b
fibonacci

How many numbers do you want? 6


[0, 1, 1, 2, 3, 5]

## Question 4

This question is about Python dictionary.

|Vaccine|Efficacy|
|-----|-------|
|Pfizer|95%|
|Moderna|95%|
|AstraZeneca|72%|
|Johnson & Johnson|66%|

Source: https://www.biospace.com/article/comparing-covid-19-vaccines-pfizer-biontech-moderna-astrazeneca-oxford-j-and-j-russia-s-sputnik-v/

In [2]:
# Create a dictionary to save the data of vaccines and their efficacy. (save 95% as 0.95)
v_dict = {'Pfizer':0.95, 'Moderna':0.95, 'AstraZeneca':0.72, 'Johnson & Johnson':0.66}

In [3]:
v = input('Which vaccine? ').capitalize()
# print the efficacy of the vaccine

print('The efficacy of', v, 'is', v_dict.get(v))

Which vaccine? pfizer
The efficacy of Pfizer is 0.95


In [14]:
# add another vaccine 'Sputnik V' with 91.4% efficacy rate to the dictionary
v_dict['Sputnik V'] = 0.914
print(v_dict)

{'Pfizer': 0.95, 'Moderna': 0.95, 'AstraZeneca': 0.72, 'Johnson & Johnson': 0.66, 'Sputnik V': 0.914}


In [15]:
# add another vaccine 'Sinovac' with 50.38% efficacy rate to the dictionary
v_dict['Sinovac'] = 0.5038
print(v_dict)

{'Pfizer': 0.95, 'Moderna': 0.95, 'AstraZeneca': 0.72, 'Johnson & Johnson': 0.66, 'Sputnik V': 0.914, 'Sinovac': 0.5038}


In [16]:
# Print vaccines with efficacy lower than 90%.
for vaccine, efficacy in v_dict.items():
    if efficacy < 0.90:
        print(vaccine)

AstraZeneca
Johnson & Johnson
Sinovac


In [17]:
# delete the Sinovac vaccine from the dictionary. 
del v_dict['Sinovac']

In [19]:
#Count the occurrence of each alphabet (no space ' ') in this sentence. 
sentence = 'the quick brown fox jumps over the lazy dog'

# Save the result in a dictionary 
ch_dict = {} 
# Use a loop to iterate all characters
# add your code here
for ch in sentence:
    if ch != ' ':
        ch_dict[ch] = sentence.count(ch)
# print the dictionary
print(ch_dict)

{'t': 2, 'h': 2, 'e': 3, 'q': 1, 'u': 2, 'i': 1, 'c': 1, 'k': 1, 'b': 1, 'r': 2, 'o': 4, 'w': 1, 'n': 1, 'f': 1, 'x': 1, 'j': 1, 'm': 1, 'p': 1, 's': 1, 'v': 1, 'l': 1, 'a': 1, 'z': 1, 'y': 1, 'd': 1, 'g': 1}


## Quesion 5

Next, we will practice with Numpy arrays.  

In [20]:
import numpy as np

In [21]:
# create a 1-D array of first 20 positive even numbers (starting with 2)
np.arange(2, 22, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [22]:
# create a 1-D array of first 20 positive odd numbers (starting with 1)
np.arange(1, 22, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [23]:
# create a 10x10 array in the following format: 
# first row: [0,1,...,9]
# second row: [10,11,...,19]
# ...
# tenth row: [90,91,...,99]
np.arange(100).reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [26]:
# Create a 10x10 array of normally distributed random values
# with mean 0 and standard deviation 1
M = np.random.normal(0, 1, (10,10))
M

array([[ 0.30609516, -1.79210971, -0.36892065, -0.27642187, -0.88178856,
        -0.71092   , -0.25253563,  0.54670306, -0.44712904,  0.7573041 ],
       [-0.66103566, -0.95413078,  0.92731252, -1.17121768, -0.09383619,
         1.41292697, -0.07644053, -0.12424843,  0.69428421,  1.09156184],
       [ 0.01756878,  0.54675739, -0.84433967, -0.33785152,  1.07330248,
        -0.28943811,  0.78934109, -1.49919022, -0.02137203,  1.94743768],
       [ 0.2965499 ,  0.28392339, -1.11953395,  0.20721678, -0.71808566,
         0.49123937,  1.08801088, -1.00938695, -1.61370964,  0.04064096],
       [-0.98256538, -0.34753835, -1.1701105 , -0.21507571, -1.68324025,
         1.25909533,  0.47568322,  0.81383243,  0.93086116,  0.38028489],
       [ 0.34673794,  1.09055558,  2.12004257,  0.71865953,  1.3288274 ,
         2.1341784 ,  0.51242957, -0.14416813, -1.36322925, -0.04406541],
       [-0.5093381 , -0.20468531, -0.37867675, -0.36184566, -0.39089923,
         1.32416973, -0.59532256, -0.91412201

In [31]:
# Count the numbers in M with an absolute value greater than 1.
count = np.sum(np.abs(M) > 1)

print(count)

33


In [35]:
# Reference: https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html

# Input the number of rows (input an integer >= 3)
r = input('Row count: ')

# Input the number of rows (input another integer >= 3)
c = input('column count: ')

# Hint: you may want to use the function int().
r = int(r)
c = int(c)
# Create a r x c array of random integers between 10 (inclusive) and 20 (exclusive).
arr = np.random.randint(10, 20, (r,c))
arr

Row count: 4
column count: 4


array([[14, 15, 10, 17],
       [14, 17, 10, 10],
       [12, 13, 14, 19],
       [14, 14, 19, 19]])

In [36]:
# output the element in the first row and the third column
print(arr[0,2])

10


In [37]:
# output the element in the second row and the last column
print(arr[1,3])

10


In [38]:
# output the second row of the array
print(arr[1,:])

[14 17 10 10]


In [39]:
# output the second last row of the array
print(arr[2,:])

[12 13 14 19]


In [40]:
# output the second column of the array
print(arr[:,1])

[15 17 13 14]


In [41]:
# output the second last column of the array
print(arr[:,2])

[10 10 14 19]


In [43]:
# output the upper-left 3x3 sub-array
print(arr[0:3, 0:3])

[[14 15 10]
 [14 17 10]
 [12 13 14]]


In [49]:
# output the bottom-left 3x3 sub-array
print(arr[1:4, 0:3])

[[14 17 10]
 [12 13 14]
 [14 14 19]]


In [47]:
# output the upper-right 3x3 sub-array
print(arr[0:3, 1:4])

[[15 10 17]
 [17 10 10]
 [13 14 19]]


In [48]:
# output the bottom-right 3x3 sub-array
print(arr[1:4, 1:4])

[[17 10 10]
 [13 14 19]
 [14 19 19]]


In [54]:
# Create a 1-D array from 1 to 50 (inclusive)
A = np.arange(1, 51)
A
# Reshape A to a 5x10 array in the following format: 
# first row: [1,...,10]
# second row: [11,...,20]
# ...
# fifth row: [41,...,50]
A_new = A.reshape(5, 10)
A_new

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [57]:
# add a row [51,...,60] to A
new_row = np.arange(51,61)
A_new = np.vstack([A_new, new_row])
A_new

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60]])

In [58]:
# split the new A (6x10) to two 3x10 arrays A1 and A2
A1, A2 = np.split(A_new, 2)
print(A1)
print(A2)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
[[31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]]


In [59]:
# Add 10 to each element of A
print('A_new + 10 =', A_new + 10)

A_new + 10 = [[11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]
 [61 62 63 64 65 66 67 68 69 70]]


In [60]:
# Calculate the square root of each element in A
print('A_new ** 2 =', A_new ** 2)

A_new ** 2 = [[   1    4    9   16   25   36   49   64   81  100]
 [ 121  144  169  196  225  256  289  324  361  400]
 [ 441  484  529  576  625  676  729  784  841  900]
 [ 961 1024 1089 1156 1225 1296 1369 1444 1521 1600]
 [1681 1764 1849 1936 2025 2116 2209 2304 2401 2500]
 [2601 2704 2809 2916 3025 3136 3249 3364 3481 3600]]


In [61]:
M

array([[ 0.30609516, -1.79210971, -0.36892065, -0.27642187, -0.88178856,
        -0.71092   , -0.25253563,  0.54670306, -0.44712904,  0.7573041 ],
       [-0.66103566, -0.95413078,  0.92731252, -1.17121768, -0.09383619,
         1.41292697, -0.07644053, -0.12424843,  0.69428421,  1.09156184],
       [ 0.01756878,  0.54675739, -0.84433967, -0.33785152,  1.07330248,
        -0.28943811,  0.78934109, -1.49919022, -0.02137203,  1.94743768],
       [ 0.2965499 ,  0.28392339, -1.11953395,  0.20721678, -0.71808566,
         0.49123937,  1.08801088, -1.00938695, -1.61370964,  0.04064096],
       [-0.98256538, -0.34753835, -1.1701105 , -0.21507571, -1.68324025,
         1.25909533,  0.47568322,  0.81383243,  0.93086116,  0.38028489],
       [ 0.34673794,  1.09055558,  2.12004257,  0.71865953,  1.3288274 ,
         2.1341784 ,  0.51242957, -0.14416813, -1.36322925, -0.04406541],
       [-0.5093381 , -0.20468531, -0.37867675, -0.36184566, -0.39089923,
         1.32416973, -0.59532256, -0.91412201

In [62]:
# Above, we have created a 10x10 array M of normally distributed random values
# with mean 0 and standard deviation 1
M.shape

(10, 10)

In [63]:
# Print the mean, standard devietion of all numbers in M
print('Mean: ', M.mean())
print('Standard Deviation: ', M.std())

Mean:  -0.018390154840036654
Standard Deviation:  0.9617875366700624


In [66]:
# Print the maximumn, 3rd quartile, median, 1st quartile, and minimum in M
print('Maximum: ', M.max())
print('3rd quartile: ', np.percentile(M, 75))
print('Median: ', np.median(M))
print('1st quartile: ', np.percentile(M, 25))
print('Minimum: ', M.min())

Maximum:  2.134178400651744
3rd quartile:  0.5467166425183803
Median:  -0.0063210002940880085
1st quartile:  -0.6735067445959179
Minimum:  -2.1257290429449927
